# Generated by Django 4.2.10 on 2024-02-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmapp', '0002_pc_remove_cartitems_pet_remove_orderitem_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='images')),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='Description about Food', max_length=255)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='component',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='component',
        ),
        migrations.DeleteModel(
            name='Pc',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmapp.food'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmapp.food'),
        ),
    ]
